"""created waitinglist table

Revision ID: 5f2ec18e8f00
Revises: 24ea1ba3af62
Create Date: 2024-07-23 02:48:53.935140

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5f2ec18e8f00'
down_revision: Union[str, None] = '24ea1ba3af62'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
